name: "Tag and build"
on:
  push:
    branches: ["main"]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.1.0
      with:
        python-version: "3.10"
    - uses: pre-commit/action@v3.0.0
  tagging:
    name: "Tagging"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo Calculated Next Tag is ${{ steps.tag_version.outputs.new_tag }}

  post_slack:
    runs-on: ubuntu-latest
    needs: tagging
    steps:
      - name: Post to a Slack channel
        if: ${{ success() }}
        id: slack_success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'sdcadmin-operator'
          slack-message: ':cool-doge: `${{github.repository}}` new version: ${{needs.tagging.outputs.next_tag}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
